using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Text.Json;
using System.Text;
using System.Net.Http;
using Microsoft.Data.Sqlite;

namespace AkinatorWeb.Pages
{
    public class GameModel : PageModel
    {
        private readonly IHttpClientFactory _clientFactory;
        private static List<AttributeItem> OrderedAttributes = new()
        {
            new("animated", "�������� ������������� ����������"),
            new("live_action", "�������� ������� �� �������� ����"),
            new("human", "�������"),
            new("non_human", "�� �������"),
            new("male", "�������� ����"),
            new("adult", "��������"),
            new("from_the_simpsons", "�� \"���������\""),
            new("is_balding", "��������"),
            new("is_a_sponge", "�������� ������"),
            new("lives_under_sea", "����� ��� �����"),
            new("is_a_rabbit", "�������� ��������"),
            new("from_looney_tunes", "�� \"���� ����\""),
            new("from_ussr", "�� ����"),
            new("is_optimistic", "������������"),
            new("from_nickelodeon", "�� Nickelodeon"),
            new("female", "�������� ����"),
            new("child", "�������"),
            new("is_a_mouse", "�������� �����"),
            new("is_an_early_disney_character", "�������� ������ ���������� ������"),
            new("wears_red_shorts", "����� ������� �����"),
            new("wears_white_gloves", "����� ����� ��������"),
            new("has_a_girlfriend_named_minnie", "����� ������� �� ����� �����"),
            new("is_a_global_icon", "�������� ������� ������"),
            new("is_a_rabbit", "�������� ��������"),
            new("from_looney_tunes", "�� \"���� ����\""),
            new("outsmarts_enemies", "����������� ������"),
            new("eats_carrots", "��� �������"),
            new("says_whats_up_doc", "������� \"What's up, doc?\""),
            new("is_a_trickster", "�������� ����������"),
            new("is_grey_and_white", "����-�����"),
            new("is_a_duck", "�������� �����"),
            new("is_greedy_or_selfish", "������ ��� �����������"),
            new("has_a_lisp", "��������"),
            new("is_black", "������"),
            new("wears_a_bow_tie", "����� �������-�������"),
            new("lives_in_stone_age", "����� � �������� ����"),
            new("lives_in_bedrock", "����� � �������"),
            new("from_hanna_barbera", "�� Hanna-Barbera"),
            new("says_yabba_dabba_doo", "������� \"Yabba Dabba Doo!\""),
            new("has_a_best_friend_named_barney", "����� ������� ����� �� ����� �����"),
            new("works_at_quarry", "�������� � �������"),
            new("wears_animal_skin_clothing", "����� ������ �� ����� ���������"),
            new("is_a_dog", "�������� �������"),
            new("solves_mysteries", "����������� �����"),
            new("travels_in_a_van_called_mystery_machine", "������������ � ������� ��� ��������� \"������ ����\""),
            new("is_cowardly", "���������"),
            new("loves_scooby_snacks", "����� �����-�������"),
            new("speaks_broken_english", "������� �� ������� ����������"),
            new("loves_food", "����� ���"),
            new("has_a_dog_as_best_friend_named_scooby", "����� ������-������� ����� �� ����� �����"),
            new("is_thin_and_lanky", "����� � ����������"),
            new("wears_a_green_shirt", "����� ������� �������"),
            new("is_a_cat", "�������� �����"),
            new("from_tom_and_jerry", "�� \"���� � ������\""),
            new("is_enemy_of_a_mouse_named_jerry", "�������� ������ ���� �� ����� ������"),
            new("often_chases_another_character", "����� ���������� ������� ���������"),
            new("is_mostly_silent", "� �������� ��������"),
            new("lives_in_a_house", "����� � ����"),
            new("is_grey_or_blue", "����� ��� �����"),
            new("is_brown", "����������"),
            new("is_a_bear", "�������� ��������"),
            new("wears_a_red_shirt", "����� ������� �������"),
            new("loves_honey", "����� ���"),
            new("lives_in_hundred_acre_wood", "����� � ���������� ����"),
            new("is_simple_minded", "������������"),
            new("from_disney", "�� ������"),
            new("is_yellow", "������"),
            new("is_a_tiger", "�������� ������"),
            new("loves_to_bounce", "����� �������"),
            new("has_a_tail_for_bouncing", "����� ����� ��� �������"),
            new("is_energetic", "����������"),
            new("is_orange_with_black_stripes", "��������� � ������� ��������"),
            new("has_a_temper", "�����������"),
            new("wears_a_sailor_shirt", "����� ���������� �������"),
            new("has_nephews_named_huey_dewey_louie", "����� ����������� �� ����� ����, ���� � ���"),
            new("is_often_unlucky", "����� ���������"),
            new("is_clumsy", "���������"),
            new("wears_a_hat", "����� �����"),
            new("says_gawrsh", "������� \"Gawrsh!\""),
            new("has_a_son_named_max", "����� ���� �� ����� ����"),
            new("is_a_pet", "�������� �������� ��������"),
            new("belongs_to_mickey_mouse", "����������� ����� �����"),
            new("does_not_speak_human_language", "�� ������� �� ������������ �����"),
            new("is_very_rich", "����� �����"),
            new("loves_money", "����� ������"),
            new("swims_in_gold_coins", "������� � ������� �������"),
            new("wears_a_top_hat_and_spats", "����� ������� � �����"),
            new("from_ducktales", "�� \"������ �������\""),
            new("is_a_pilot", "�������� �������"),
            new("is_clumsy_pilot", "��������� �����"),
            new("works_for_scrooge_mcduck", "�������� �� ������� �������"),
            new("wears_a_flight_helmet", "����� ������ ����"),
            new("is_a_ninja_turtle", "�������� ����������-������"),
            new("wears_blue_mask", "����� ����� �����"),
            new("uses_katanas", "���������� ������"),
            new("is_the_leader_of_the_team", "�������� ������� �������"),
            new("lives_in_sewers", "����� � �����������"),
            new("eats_pizza", "��� �����"),
            new("is_the_most_disciplined", "����� ������������������"),
            new("wears_orange_mask", "����� ��������� �����"),
            new("uses_nunchucks", "���������� �������"),
            new("is_the_jokester_of_the_team", "�������� �������� � �������"),
            new("loves_pizza_very_much", "����� ����� �����"),
            new("says_cowabunga", "������� \"Cowabunga!\""),
            new("uses_surfer_slang", "���������� ����� ��������"),
            new("is_a_robot", "�������� �������"),
            new("can_transform", "����� ������������������"),
            new("transforms_into_a_truck", "���������������� � ��������"),
            new("is_a_leader", "�������� �������"),
            new("fights_for_good", "��������� �� �����"),
            new("from_transformers", "�� \"�������������\""),
            new("is_an_autobot", "�������� ���������"),
            new("uses_a_blaster", "���������� �������"),
            new("is_a_villain", "�������� �������"),
            new("fights_for_evil", "��������� �� ���"),
            new("is_a_decepticon", "�������� ������������"),
            new("enemy_of_optimus_prime", "���� �������� ������"),
            new("transforms_into_a_gun", "���������������� � ��������"),
            new("has_super_strength", "�������� ����������"),
            new("says_i_have_the_power", "������� \"� ���� ���� ����!\""),
            new("has_a_secret_identity_as_prince_adam", "����� ��������� �������� - ����� ����"),
            new("rides_a_green_tiger_named_battle_cat", "����� �� ������� ����� �� ����� ������ ���"),
            new("uses_a_magic_sword", "���������� ��������� ���"),
            new("from_he_man_and_the_masters_of_the_universe", "�� \"��-��� � ���������� ���������\""),
            new("has_skull_for_a_face", "����� ����� ������ ����"),
            new("enemy_of_he_man", "���� ��-����"),
            new("seeks_power", "���� ������"),
            new("uses_magic_staff", "���������� ���������� �����"),
            new("lives_on_planet_eternia", "����� �� ������� �������"),
            new("is_lazy", "�������"),
            new("loves_lasagna", "����� �������"),
            new("hates_mondays", "��������� ������������"),
            new("has_a_dog_companion_named_odie", "����� ������-���������� �� ����� ���"),
            new("lives_with_human_owner_named_jon_arbuckle", "����� � ���������-�������� �� ����� ���� ������"),
            new("from_garfield", "�� \"��������\""),
            new("from_comic_strip", "�� ��������"),
            new("is_simple_minded", "������������"),
            new("lives_with_garfield", "����� � ���������"),
            new("is_owned_by_jon_arbuckle", "����������� ����� �������"),
            new("has_floppy_ears", "����� ������� ���"),
            new("has_a_long_tongue", "����� ������� ����"),
            new("owns_a_cat_named_garfield", "������� ����� �� ����� �������"),
            new("owns_a_dog_named_odie", "������� ������� �� ����� ���"),
            new("is_awkward", "��������"),
            new("is_a_cartoonist", "�������� ��������������"),
            new("wears_glasses", "����� ����"),
            new("is_a_bird", "�������� ������"),
            new("is_a_woodpecker", "�������� ������"),
            new("has_a_distinctive_laugh", "����� ����������� ����"),
            new("wears_gloves", "����� ��������"),
            new("has_red_crest", "����� ������� �������"),
            new("is_a_sailor", "�������� �������"),
            new("gains_strength_from_eating_spinach", "�������� ����, ���� ������"),
            new("has_big_forearms", "����� ������� ����������"),
            new("has_one_eye_closed_or_squinting", "���� ���� ������ ��� ��������"),
            new("has_a_girlfriend_named_olive_oyl", "����� ������� �� ����� ���� ���"),
            new("smokes_a_pipe", "����� ������"),
            new("is_very_thin", "����� �����"),
            new("wears_red_dress", "����� ������� ������"),
            new("is_the_girlfriend_of_popeye", "�������� �������� �����"),
            new("is_often_in_distress", "����� �������� � ����"),
            new("is_enemy_of_popeye", "���� �����"),
            new("is_physically_strong", "��������� �������"),
            new("wears_a_cap", "����� �����"),
            new("has_a_beard", "����� ������"),
            new("is_a_bully", "�������� �������"),
            new("is_a_panther", "�������� ��������"),
            new("is_pink", "�������"),
            new("accompanied_by_jazzy_music", "�������������� �������� �������"),
            new("is_a_detective", "�������� ����������"),
            new("is_incompetent_detective", "�������������� ��������"),
            new("from_the_pink_panther_films", "�� ������� � \"������� �������\""),
            new("causes_chaos", "�������� ����"),
            new("speaks_with_a_french_accent", "������� � ����������� ��������"),
            new("is_an_aardvark", "�������� �����������"),
            new("goes_to_school", "����� � �����"),
            new("from_arthur", "�� \"������\""),
            new("has_a_younger_sister_named_dw", "����� ������� ������ �� ����� ��-����-�"),
            new("is_an_explorer", "�������� ��������������/����������������"),
            new("asks_questions_to_viewer", "������ ������� �������"),
            new("has_a_monkey_friend_named_boots", "����� �����-��������� �� ����� ��������"),
            new("speaks_some_spanish", "������� ������� ��-��������"),
            new("carries_a_backpack", "����� ������"),
            new("is_a_monkey", "�������� ���������"),
            new("wears_red_boots", "����� ������� ������"),
            new("is_a_companion_to_dora_the_explorer", "�������� ��������� ����-���������������"),
            new("is_purple", "����������"),
            new("rescues_animals", "������� ��������"),
            new("is_cousin_of_dora", "�������� ������� ����"),
            new("from_go_diego_go", "�� \"������, �����, ������!\""),
            new("speaks_spanish", "������� ��-��������"),
            new("has_a_jaguar_companion", "����� ����������-������"),
            new("is_a_pig", "�������� �������"),
            new("loves_jumping_in_muddy_puddles", "����� ������� �� ������� �����"),
            new("has_a_younger_brother_named_george", "����� �������� ����� �� ����� ������"),
            new("from_peppa_pig", "�� \"������ �����\""),
            new("has_british_accent", "����� ���������� ������"),
            new("loves_dinosaurs", "����� ����������"),
            new("is_younger_brother_of_peppa", "�������� ������� ������ �����"),
            new("says_dinosaur", "������� \"��������\""),
            new("from_russia", "�� ������"),
            new("is_very_active_or_mischievous", "����� �������� ��� �������"),
            new("lives_near_a_forest", "����� ����� � �����"),
            new("has_a_bear_friend_named_medved", "����� �����-������� �� ����� �������"),
            new("from_masha_and_the_bear", "�� \"���� � �������\""),
            new("lives_in_a_forest_house", "����� � ������ ����"),
            new("is_retired_circus_performer", "������ �������� ������"),
            new("takes_care_of_a_girl_named_masha", "��������� � ������ �� ����� ����"),
            new("does_not_speak_human_language_much", "���� ������� �� ������������ �����"),
            new("is_a_hedgehog", "�������� ������"),
            new("gets_lost_in_fog", "�������� � ������"),
            new("searches_for_a_bear", "���� �������"),
            new("carries_a_bundle", "����� ������"),
            new("from_philosophical_cartoon", "�� ������������ �����������"),
            new("is_very_kind", "����� ������"),
            new("has_mouse_enemies", "����� ������-�����"),
            new("says_guys_lets_live_together_friendly", "������� \"������, ������� ���� ������!\""),
            new("sings_songs", "���� �����"),
            new("has_a_small_pig_friend_named_pyatachok", "����� �����-��������� �� ����� �������"),
            new("is_friend_of_vinni_puh_soviet", "�������� ������ �����-���� (����������)"),
            new("is_small", "���������"),
            new("lives_on_the_roof", "����� �� �����"),
            new("has_a_propeller_on_his_back", "����� ��������� �� �����"),
            new("is_selfish_or_boastful", "����������� ��� ����������"),
            new("loves_jam_and_sweets", "����� ������� � ��������"),
            new("is_friend_of_a_boy_named_malysh", "�������� ������ �������� �� ����� �����"),
            new("wishes_for_a_dog", "������� � ������"),
            new("lives_with_parents", "����� � ����������"),
            new("is_friend_of_karlson", "�������� ������ ��������"),
            new("runs_away_from_home", "������� �� ����"),
            new("lives_in_a_village", "����� � �������"),
            new("has_talking_pets", "����� ��������� ��������"),
            new("from_prostokvashino", "�� \"�������������\""),
            new("is_economical_or_practical", "��������� ��� ����������"),
            new("owns_a_cow", "������� �������"),
            new("wears_a_vest", "����� �����"),
            new("has_a_moustache", "����� ���"),
            new("loves_hunting", "����� �����"),
            new("uses_a_photo_gun", "���������� ���������"),
            new("is_a_wolf", "�������� ������"),
            new("chases_a_rabbit_named_zayac", "�������� �� ������ �� ����� ����"),
            new("is_a_hooligan", "�������� ���������"),
            new("says_nu_pogodi", "������� \"��, ������!\""),
            new("wears_a_shirt_and_pants", "����� ������� � �����"),
            new("is_chased_by_a_wolf_named_volk", "��� ���������� ���� �� ����� ����"),
            new("is_resourceful", "����������"),
            new("wears_pants_or_shorts", "����� ����� ��� �����"),
            new("has_big_ears", "����� ������� ���"),
            new("is_friend_of_a_crocodile_named_gena", "�������� ������ ��������� �� ����� ����"),
            new("works_at_a_zoo_at_first", "������� �������� � ��������"),
            new("falls_out_of_orange_box", "�������� �� ������� � �����������"),
            new("is_a_crocodile", "�������� ����������"),
            new("works_at_a_zoo", "�������� � ��������"),
            new("plays_accordion", "������ �� ��������"),
            new("is_lonely", "��������"),
            new("wears_a_suit", "����� ������"),
            new("has_a_pet_rat_named_larska", "����� �������� ����� �� ����� �������"),
            new("carries_a_purse", "����� �������"),
            new("wears_a_large_hat", "����� ������� �����"),
            new("likes_to_do_mischief", "����� ������������"),
            new("is_a_parrot", "�������� ��������"),
            new("imitates_human_speech", "��������� ������������ ����"),
            new("is_boastful", "����������"),
            new("lives_in_a_city_apartment", "����� � ��������� ��������"),
            new("is_blue_and_yellow", "����-������"),
            new("is_a_house_spirit", "�������� �������"),
            new("tells_tales", "������������ ������"),
            new("wears_a_tunic_and_bast_shoes", "����� ������ � �����"),
            new("lives_on_earth_alone", "����� ���� �� �����"),
            new("cleans_up_trash", "������� �����"),
            new("loves_old_movies", "����� ������ ������"),
            new("collects_items", "��������������� ��������"),
            new("has_a_pet_cockroach", "����� ��������� ��������"),
            new("from_pixar", "�� Pixar"),
            new("has_tread_wheels", "����� ��������/�����"),
            new("comes_from_space", "��������� �� �������"),
            new("is_a_probe", "�������� ������"),
            new("can_fly", "����� ������"),
            new("has_a_laser_arm", "����� �������� ����"),
            new("looks_sleek_and_white", "�������� ������� � �����"),
            new("searches_for_plant_life", "���� ������������ �����"),
            new("is_an_ogre", "�������� �����"),
            new("lives_in_a_swamp", "����� �� ������"),
            new("is_grumpy_at_first", "������� ���������"),
            new("has_a_donkey_friend_named_donkey", "����� �����-���� �� ����� ����"),
            new("marries_a_princess_named_fiona", "������� �� ��������� �� ����� �����"),
            new("from_dreamworks", "�� Dreamworks"),
            new("is_green", "�������"),
            new("is_a_donkey", "�������� �����"),
            new("talks_a_lot", "����� �������������"),
            new("is_friend_of_shrek", "�������� ������ �����"),
            new("marries_a_dragon", "������� �� �������"),
            new("is_a_princess", "�������� ����������"),
            new("knows_martial_arts", "����� ������ ���������"),
            new("marries_shrek", "������� ����� �� �����"),
            new("transforms_into_an_ogre", "������������ � ����"),
            new("has_a_human_and_ogre_form", "����� ������������ ����� � ����� ����"),
            new("is_a_lion", "�������� �����"),
            new("lives_in_a_zoo_at_first", "������� ����� � ��������"),
            new("loves_to_perform", "����� ���������"),
            new("gets_to_madagascar", "�������� �� ����������"),
            new("has_a_mane", "����� �����"),
            new("is_a_zebra", "�������� ������"),
            new("wants_to_be_wild", "����� ���� �����"),
            new("has_black_and_white_stripes", "����� �����-����� ������"),
            new("is_a_giraffe", "�������� �������"),
            new("is_a_hypochondriac", "����������"),
            new("has_a_long_neck", "����� ������� ���"),
            new("is_brown_and_yellow", "���������-������"),
            new("is_a_hippo", "�������� ���������"),
            new("is_confident", "���������"),
            new("is_large_in_size", "������� �� �������"),
            new("is_grey", "�����"),
            new("is_a_lemur", "�������� �������"),
            new("thinks_he_is_important", "������, ��� �� ������"),
            new("loves_to_dance", "����� ���������"),
            new("from_madagascar", "�� \"�����������\""),
            new("has_a_servant_named_maurice", "����� ����� �� ����� �����"),
            new("wears_a_leaf_crown", "����� ������ �� �������"),
            new("is_a_penguin", "�������� ���������"),
            new("is_a_strategist", "�������� ���������"),
            new("is_part_of_a_small_commando_team", "�������� ������ ��������� ������� ���������"),
            new("speaks_in_military_jargon", "������� ������� ��������"),
            new("is_black_and_white", "�����-�����"),
            new("is_a_panda", "�������� ������"),
            new("learns_kung_fu", "������ ����-��"),
            new("is_the_dragon_warrior", "�������� ������ �������"),
            new("works_in_a_noodle_shop_at_first", "������� �������� � ���������"),
            new("is_clumsy_but_powerful", "���������, �� �������"),
            new("is_a_red_panda", "�������� ������� ������"),
            new("is_a_kung_fu_master", "�������� �������� ����-��"),
            new("trains_po", "��������� ��"),
            new("lives_in_a_temple", "����� � �����"),
            new("is_initially_skeptical_of_po", "���������� ����������� ��������� � ��"),
            new("lives_on_an_island", "����� �� �������"),
            new("is_connected_to_the_ocean", "������ � �������"),
            new("goes_on_a_voyage", "������������ � ��������"),
            new("has_a_rooster_pet_named_heihei", "����� ������-������� �� ����� ���-���"),
            new("does_not_have_a_love_interest", "�� ����� ��������� ��������"),
            new("is_a_demigod", "�������� ���������"),
            new("can_shapeshift", "����� ������ �����"),
            new("has_a_magic_fish_hook", "����� ��������� ���������� ����"),
            new("travels_with_moana", "������������ � ������"),
            new("is_covered_in_magical_tattoos", "������ ����������� ������������"),
            new("lost_his_fish_hook", "������� ���� ���������� ����"),
            new("has_very_long_hair", "����� ����� ������� ������"),
            new("was_locked_in_a_tower", "��� ������ � �����"),
            new("uses_a_frying_pan_as_weapon", "���������� ���������� ��� ������"),
            new("has_a_chameleon_friend_named_pascal", "����� �����-��������� �� ����� �������"),
            new("is_a_lost_princess", "�������� ���������� ����������"),
            new("is_a_thief_at_first", "������� �������� �����"),
            new("has_a_wanted_poster", "����� ������ \"�������������\""),
            new("travels_with_rapunzel", "������������ � ���������"),
            new("is_also_known_as_eugene_fitzherbert", "����� �������� ��� ����� ����������"),
            new("is_charming_and_sarcastic", "�������������� � ������������"),
            new("falls_in_love_with_a_princess", "���������� � ���������"),
            new("is_a_viking", "�������� ��������"),
            new("befriends_a_dragon_named_toothless", "������ � �������� �� ����� ��������"),
            new("is_initially_unskilled_viking", "���������� �������� ������"),
            new("from_how_to_train_your_dragon", "�� \"��� ��������� �������\""),
            new("has_prosthetic_leg", "����� ������ ����"),
            new("is_inventive", "���������������"),
            new("is_a_dragon", "�������� ��������"),
            new("is_black_dragon", "������ ������"),
            new("is_a_night_fury", "�������� ������ ������"),
            new("cannot_fly_alone", "�� ����� ������ ����"),
            new("is_loyal", "���������"),
            new("is_skilled_archer", "�������� ������� ��������"),
            new("has_curly_red_hair", "����� �������� ����� ������"),
            new("rides_a_horse_named_angus", "����� �� ������ �� ����� �����"),
            new("rebels_against_tradition", "������� ������ ��������"),
            new("uses_a_bow", "���������� ���"),
            new("wants_to_be_an_explorer", "����� ����� ��������������"),
            new("is_married_to_carl_fredricksen", "������� �� ������ ������������"),
            new("does_not_appear_for_most_of_movie", "�� ���������� ������� ����� ������"),
            new("travels_in_a_house_with_balloons", "������������ � ���� � ���������� ������"),
            new("is_a_widower", "������"),
            new("is_grumpy_at_first", "������� ���������"),
            new("is_a_retired_balloon_salesman", "��������� �������� ��������� �����"),
            new("uses_a_cane", "���������� ������"),
            new("is_a_wilderness_explorer", "�������� ���� ������������/�������������� ����� �������"),
            new("helps_an_elderly_man", "�������� �������� �������"),
            new("is_chubby", "������"),
            new("wears_a_scout_uniform", "����� ����� ������"),
            new("has_a_dog_friend_who_talks_named_dug", "����� �����-������, ������� �������, �� ����� ���"),
            new("is_a_car", "�������� �������"),
            new("is_a_race_car", "�������� �������� �������"),
            new("is_red", "�������"),
            new("lives_in_radiator_springs", "����� � ��������-�������"),
            new("has_a_best_friend_who_is_a_tow_truck_named_mater", "����� ������� ����� - ��������� �� ����� ����"),
            new("is_a_tow_truck", "�������� �����������"),
            new("is_rusty", "������"),
            new("is_best_friend_of_lightning_mcqueen", "�������� ������ ������ ������ ��������"),
            new("loves_to_go_tractor_tipping", "����� ������������ ��������"),
            new("is_a_wizard", "�������� �����������"),
            new("goes_to_magic_school_hogwarts", "����� � ����� ����� ��������"),
            new("has_a_scar_on_forehead", "����� ���� �� ���"),
            new("is_the_main_protagonist", "�������� ������� ������"),
            new("from_harry_potter", "�� \"����� �������\""),
            new("speaks_to_snakes", "������� �� ������"),
            new("is_known_as_the_boy_who_lived", "�������� ��� �������, ������� �����"),
            new("has_an_owl_pet_named_hedwig", "����� ����-������� �� ����� �����"),
            new("is_very_smart", "����� �����"),
            new("is_friend_of_harry_potter", "�������� ������ ����� �������"),
            new("uses_magic_wand", "���������� ��������� �������"),
            new("is_muggle_born", "������� ��������"),
            new("has_red_hair", "����� ����� ������"),
            new("comes_from_a_large_wizarding_family", "���������� �� ������� ��������� �����"),
            new("is_afraid_of_spiders", "������ ������"),
            new("is_loyal", "���������"),
            new("wears_black_armor_and_helmet", "����� ������ ������� � ����"),
            new("uses_the_dark_side_of_the_force", "���������� ������ ������� ����"),
            new("uses_a_red_lightsaber", "���������� ������� �������� ���"),
            new("is_father_of_luk_skaywalker_and_leya_organa", "�������� ����� ���� ���������� � ��� ������"),
            new("from_star_wars", "�� \"�������� ����\""),
            new("breathes_loudly", "������ �����"),
            new("was_a_jedi", "��� �������"),
            new("is_a_jedi", "�������� �������"),
            new("uses_the_force", "���������� ����"),
            new("uses_a_lightsaber", "���������� �������� ���"),
            new("is_a_farm_boy_at_first", "������� ���������� ������"),
            new("discovers_he_has_a_twin_sister_leya", "������������, ��� � ���� ���� ������-������� ���"),
            new("fights_against_the_empire", "��������� ������ �������"),
            new("destroys_death_star", "���������� ������ ������"),
            new("is_a_smuggler", "�������� ���������������"),
            new("owns_a_famous_spaceship_millennium_falcon", "������� ���������� ����������� �������� \"������������ �����\""),
            new("has_a_wookiee_friend_named_chewbacca", "����� �����-���� �� ����� �������"),
            new("is_sarcastic", "������������"),
            new("flies_kessel_run_in_less_than_12_parsecs", "�������� ����������� ��������� ����� ��� �� 12 ��������"),
            new("is_a_leader_of_the_rebellion", "�������� ������� �������������� �������"),
            new("has_twin_brother_luk_skywalker", "����� �����-�������� ���� ����������"),
            new("wears_distinctive_hair_buns", "����� ����������� ��������-\"�������\""),
            new("is_captured_by_darth_vader", "��������� ������ ��������"),
            new("is_an_archaeologist", "�������� ����������"),
            new("uses_a_whip", "���������� ����"),
            new("wears_a_fedora_hat", "����� �����-������"),
            new("fears_snakes", "������ ����"),
            new("seeks_ancient_artifacts", "���� ������� ���������"),
            new("from_indiana_jones", "�� \"������� ������\""),
            new("is_also_a_professor", "����� �������� �����������"),
            new("is_from_the_future", "������ �� ��������"),
            new("is_initially_an_antagonist", "���������� �������� ������������"),
            new("says_i_ll_be_back", "������� \"� �������\""),
            new("has_a_metal_skeleton_under_skin", "����� ������������� ������ ��� �����"),
            new("from_the_terminator_franchise", "�� �������� \"����������\""),
            new("protects_john_connor", "�������� ����� �������"),
            new("has_red_eyes", "����� ������� �����"),
            new("is_a_mother_of_future_leader_john_connor", "�������� ������� �������� ������ ����� �������"),
            new("fights_against_robots", "��������� ������ �������"),
            new("becomes_a_strong_warrior", "���������� ������� ������������"),
            new("is_a_waitress_at_first", "������� �������� �����������"),
            new("is_paranoid", "��������"),
            new("travels_through_time", "������������ �� �������"),
            new("uses_a_delorean_to_time_travel", "���������� �������� ��� ����������� �� �������"),
            new("plays_guitar", "������ �� ������"),
            new("is_friend_of_a_scientist_named_doc_brown", "�������� ������ ������� �� ����� ��� �����"),
            new("from_back_to_the_future", "�� \"����� � �������\""),
            new("is_afraid_of_being_called_chicken", "������, ����� ��� �������� \"���������\""),
            new("skateboards", "�������� �� ����������"),
            new("is_a_scientist", "�������� ������"),
            new("invents_a_time_machine", "���������� ������ �������"),
            new("has_wild_white_hair", "����� ������������ ����� ������"),
            new("is_friend_of_marty_mcfly", "�������� ������ ����� �������"),
            new("often_says_great_scott", "����� ������� \"Great Scott!\""),
            new("has_a_dog_pet_named_einstein", "����� ������-������� �� ����� ��������"),
            new("tells_his_life_story_on_a_bench", "������������ ������� ����� ����� �� ��������"),
            new("from_forrest_gump", "�� \"�������� �����\""),
            new("loves_shrimp", "����� ��������"),
            new("meets_several_famous_people", "��������� ���������� ���������� �����"),
            new("says_life_is_like_a_box_of_chocolates", "������� \"����� ��� ������� ���������� ������\""),
            new("is_a_boxer", "�������� ��������"),
            new("is_from_philadelphia", "�� �����������"),
            new("fights_famous_opponents", "��������� � ���������� ������������"),
            new("is_an_underdog", "�������� �����������"),
            new("runs_up_famous_steps", "����� �� ��������� ����������"),
            new("from_rocky_franchise", "�� �������� \"�����\""),
            new("is_left_handed", "�����"),
            new("is_a_police_officer", "�������� �������� �������"),
            new("fights_terrorists_alone_in_a_building", "� �������� ��������� � ������������ � ������"),
            new("is_often_barefoot_and_bloody", "����� ��� � � �����"),
            new("says_yippee_ki_yay", "������� \"Yippee-ki-yay\""),
            new("from_die_hard_franchise", "�� �������� \"������� ������\""),
            new("from_new_york_city", "�� ���-�����"),
            new("is_eccentric_or_quirky", "������������� ��� �����������"),
            new("wears_dreadlocks_and_hat", "����� ����� � �����"),
            new("from_pirates_of_the_caribbean", "�� \"������� ���������� ����\""),
            new("uses_a_compass_that_points_to_what_he_wants_most", "���������� ������, ������� ��������� �� ��, ���� �� ������ ����� ������"),
            new("volunteers_for_a_deadly_competition_the_hunger_games", "����������� ��������� � ����������� ������������ - �������� �����"),
            new("starts_a_rebellion", "�������� ���������"),
            new("is_from_district_12", "�� ��������� 12"),
            new("from_the_hunger_games", "�� \"�������� ���\""),
            new("hunts_to_feed_her_family", "��������, ����� ���������� �����"),
            new("is_a_baker_s_son", "��� ������"),
            new("competes_in_a_deadly_competition_the_hunger_games", "��������� � ����������� ������������ - �������� �����"),
            new("can_camouflage", "����� �������������"),
            new("is_in_love_with_katniss", "������� � �������"),
            new("has_horns", "����� ����"),
            new("wears_dark_clothing", "����� ������ ������"),
            new("is_a_powerful_magic_user", "�������� �������������� ������������� �����"),
            new("is_initially_a_villain", "���������� �������� �������"),
            new("from_sleeping_beauty_or_maleficent_film", "�� \"������ ���������\" ��� ������ \"�����������\""),
            new("curses_a_baby_princess", "���������� ������������� ���������"),
            new("is_a_pet_detective", "�������� ���������� �� ������� �������� ��������"),
            new("has_a_distinctive_hairstyle", "����� ����������� ��������"),
            new("talks_in_a_funny_way", "������ �������������"),
            new("from_ace_ventura_franchise", "�� �������� \"��� �������\""),
            new("loves_animals", "����� ��������"),
            new("says_all_righty_then", "������� \"All righty then!\""),
            new("lives_in_a_simulated_reality_the_matrix", "����� � �������������� ���������� - �������"),
            new("is_known_as_the_one", "�������� ��� ���������"),
            new("can_manipulate_physics_in_the_matrix", "����� ��������� ������� � �������"),
            new("wears_a_black_trench_coat", "����� ������ ����"),
            new("is_a_computer_programmer_at_first", "������� �������� ������������ �������������"),
            new("from_the_matrix_franchise", "�� �������� \"�������\""),
            new("learns_kung_fu_instantly", "��������� ������� ����-��"),
            new("is_a_leader_of_rebels_zion", "�������� ������� ���������� �� �����"),
            new("wears_a_trench_coat_and_sunglasses", "����� ���� � ��������� ����"),
            new("believes_in_neo", "����� � ���"),
            new("offers_a_choice_of_pills", "���������� ����� ��������"),
            new("is_skilled_in_martial_arts", "������ � ������ ����������"),
            new("is_captain_of_the_nebuchadnezzar", "�������� ��������� \"��������������\""),
            new("is_a_skilled_hacker", "�������� ������� �������"),
            new("wears_black_leather_clothing", "����� ������ ������� ������"),
            new("is_in_love_with_neo", "�������� � ���"),
            new("rides_a_motorcycle_in_chase", "���� �� ��������� �� ����� ������"),
            new("is_a_ranger_at_first", "������� �������� ����������"),
            new("is_rightful_king_of_gondor", "�������� �������� ������� �������"),
            new("uses_a_sword_named_anduril", "���������� ��� �� ����� �������"),
            new("is_part_of_a_fellowship", "�������� ������ �������� ������"),
            new("is_in_love_with_an_elf_named_arwen", "������� � �������� �� ����� �����"),
            new("from_the_lord_of_the_rings", "�� \"���������� �����\""),
            new("is_over_80_years_old", "������ 80 ���"),
            new("is_old", "������/�������"),
            new("wears_grey_or_white_robes", "����� ����� ��� ����� ������"),
            new("uses_a_staff", "���������� �����"),
            new("guides_the_protagonist_frodo", "����� �������� ����� �����"),
            new("fights_a_balrog_in_moria", "��������� � �������� � �����"),
            new("lives_in_the_shire", "����� � ����"),
            new("carries_a_powerful_ring_the_one_ring", "����� �������������� ������ - ������ ������"),
            new("travels_to_mount_doom", "������������ � ������� ����"),
            new("has_hairy_feet", "����� �������� ������"),
            new("is_a_gardener", "�������� ����������"),
            new("is_friend_and_companion_of_frodo", "�������� ������ � ��������� �����"),
            new("is_very_loyal", "���������"),
            new("kills_shelob", "������� �����"),
            new("is_from_gondor", "�� �������"),
            new("wants_to_use_the_ring", "����� ������������ ������"),
            new("dies_heroically", "�������� ����������"),
            new("uses_a_shield", "���������� ���"),
            new("is_an_elf", "�������� ������"),
            new("has_blonde_hair", "����� ������� ������"),
            new("is_prince_of_mirkwood", "�������� ������� ���������"),
            new("is_a_dwarf", "�������� ������"),
            new("uses_an_axe", "���������� �����"),
            new("argues_with_legolas", "������ � ���������"),
            new("is_son_of_gloin", "�������� ����� ������"),
            new("is_enemy_of_batman", "���� �������"),
            new("has_a_permanent_smile_or_grin", "����� ���������� ������ ��� �������"),
            new("wears_purple_suit", "����� ���������� ������"),
            new("is_insane", "��������"),
            new("is_a_clown_like_criminal", "�������� ������������, ������� �� ������"),
            new("from_dc_comics", "�� DC Comics"),
            new("has_white_skin_and_green_hair", "����� ����� ���� � ������� ������"),
            new("is_a_superhero", "�������� �����������"),
            new("does_not_have_superpowers", "�� ����� �����������������"),
            new("uses_gadgets", "���������� �������"),
            new("wears_a_bat_themed_costume", "����� ������ � ����� ������� ����"),
            new("lives_in_gotham_city", "����� � �����-����"),
            new("has_a_secret_identity_as_bruce_wayne", "����� ��������� �������� - ���� ����"),
            new("is_a_billionaire", "�������� ������������"),
            new("operates_at_night", "��������� �� �����"),
            new("is_a_butler", "�������� ���������"),
            new("works_for_bruce_wayne", "�������� �� ����� �����"),
            new("helps_batman", "�������� �������"),
            new("lives_in_wayne_manor", "����� � �������� ������"),
            new("is_british", "��������"),
            new("is_a_father_figure", "�������� ��������� �������"),
            new("is_a_spy", "�������� �������"),
            new("works_for_british_secret_service", "�������� �� ���������� ��������� ������"),
            new("travels_the_world", "������������ �� ����"),
            new("is_known_as_007", "�������� ��� 007"),
            new("likes_martinis_shaken_not_stirred", "����� �������, �����������, �� �� ���������"),
            new("from_james_bond_franchise", "�� �������� � ������� �����"),
            new("drives_fast_cars", "����� ������� ������"),
            new("is_a_program", "�������� ����������"),
            new("can_copy_himself", "����� ���������� ����"),
            new("is_an_antagonist", "�������� ������������"),
            new("wants_to_escape_the_matrix", "����� ������� �� �������"),
            new("owns_a_chocolate_factory", "������� ���������� ��������"),
            new("is_eccentric", "�������������"),
            new("offers_a_tour", "���������� ���������"),
            new("wears_a_top_hat", "����� �������"),
            new("from_charlie_and_the_chocolate_factory", "�� \"����� � ���������� �������\""),
            new("has_small_workers_called_oompa_loompas", "����� ��������� ���������� �� ����� ����-�������"),
            new("is_poor", "������"),
            new("finds_a_golden_ticket", "������� ������� �����"),
            new("is_good_hearted", "��������������"),
            new("goes_on_a_factory_tour", "������������ �� ��������� �� �������"),
            new("lives_with_his_grandparents", "����� � �������� � ��������"),
            new("inherits_the_factory", "��������� �������"),
            new("has_scissors_for_hands", "����� ������� ������ ���"),
            new("was_created_by_an_inventor", "��� ������ �������������"),
            new("is_gentle_despite_appearance", "������, �������� �� ���������"),
            new("is_pale_with_dark_hair", "������� � ������� ��������"),
            new("lives_in_a_castle_at_first", "������� ����� � �����"),
            new("from_edward_scissorhands", "�� \"������� ����-�������\""),
            new("can_create_ice_sculptures", "����� ��������� ������� ����������"),
            new("is_not_very_intelligent", "�� ����� �����"),
            new("travels_with_a_friend_named_lloyd", "������������ � ������ �� ����� �����"),
            new("wears_distinctive_orange_tuxedo", "����� ����������� ��������� �������"),
            new("from_dumb_and_dumber", "�� \"����� � ��� �����\""),
            new("owns_a_dog_van", "������� �������� � ���� ������"),
            new("rides_a_mini_bike", "����� �� ����-�����"),
            new("has_a_chipped_tooth", "����� �������� ���"),
            new("is_a_police_detective", "�������� �������� �������"),
            new("is_new_to_the_city", "��������� � ������"),
            new("investigates_serial_murders", "���������� �������� ��������"),
            new("is_partnered_with_an_older_detective_named_somerset", "�������� � ���� � ������� ���������� �� ����� ��������"),
            new("is_impetuous", "������������"),
            new("from_se7en", "�� \"����\""),
            new("is_married", "�����"),
            new("is_about_to_retire", "���������� �� ������"),
            new("is_partnered_with_a_younger_detective_named_mills", "�������� � ���� � ������� ���������� �� ����� �����"),
            new("is_methodical", "����������"),
            new("is_wise", "������"),
            new("is_a_serial_killer", "�������� �������� �������"),
            new("murders_based_on_seven_deadly_sins", "��������� ��������, ���������� �� ���� �������� ������"),
            new("is_methodical_and_intelligent", "���������� � �����"),
            new("turns_himself_in", "������� �������"),
            new("his_face_is_initially_hidden", "��� ���� ���������� ������"),
            new("turns_green_when_angry", "��������, ����� ������"),
            new("is_part_of_avengers_team", "�������� ������ ������� ���������"),
            new("from_marvel", "�� Marvel"),
            new("is_indestructible", "��������"),
            new("grows_in_size", "������������� � �������"),
            new("wears_a_powered_suit", "����� ������������������� ������"),
            new("is_an_inventor_named_tony_stark", "�������� ������������� �� ����� ���� �����"),
            new("is_witty", "����������"),
            new("has_an_arc_reactor", "����� ������� �������"),
            new("is_a_super_soldier", "�������� �������������"),
            new("was_frozen_in_ice", "��� ��������� �� ����"),
            new("is_from_the_1940s", "�� 1940-� �����"),
            new("is_honorable", "�����������"),
            new("is_a_god", "�������� �����"),
            new("uses_a_hammer_or_axe_mjolnir_stormbreaker", "���������� ����� ��� ����� (��������, ����������)"),
            new("controls_lightning", "��������� �������"),
            new("is_from_another_realm_asgard", "�� ������� ���� - �������"),
            new("has_a_brother_named_loki", "����� ����� �� ����� ����"),
            new("is_a_master_of_martial_arts", "�������� �������� ������ ��������"),
            new("is_from_russia", "�� ������"),
            new("wears_black_suit", "����� ������ ������"),
            new("can_shoot_webs", "����� �������� ��������"),
            new("can_climb_walls", "����� ������ �� ������"),
            new("has_a_spider_sense", "����� ������ �����"),
            new("is_initially_a_high_school_student", "���������� �������� ����������������"),
            new("was_bitten_by_a_radioactive_spider", "��� ������ ������������� ������"),
            new("is_a_sorcerer", "�������� ��������"),
            new("was_a_surgeon", "��� ��������"),
            new("uses_magic_from_hands", "���������� ����� ������"),
            new("has_eye_of_agamotto", "����� ���� ��������"),
            new("is_a_space_traveler", "�������� ����������� ����������������"),
            new("is_a_leader_of_guardians_of_the_galaxy", "�������� ������� ������� ���������"),
            new("loves_old_music", "����� ������ ������"),
            new("uses_blasters", "���������� ��������"),
            new("carries_a_walkman", "����� ������"),
            new("is_a_tree_like_creature", "������������� ��������"),
            new("can_only_say_i_am_groot", "����� ������� ������ \"� ���� ����\""),
            new("is_friend_of_rocket", "�������� ������ ������"),
            new("can_regenerate", "����� ��������������"),
            new("is_very_strong", "����� �������"),
            new("is_a_raccoon", "�������� ������"),
            new("is_genetically_engineered", "����������� �������������"),
            new("is_a_skilled_marksman", "�������� ������ ��������"),
            new("is_friend_of_groot", "�������� ������ �����"),
            new("is_a_master_of_explosives", "�������� �������� ����������"),
            new("is_in_love_with_a_farm_boy_named_westley", "�������� � ����������� ����� �� ����� ������"),
            new("is_captured_by_villains", "��������� ��������"),
            new("is_beautiful", "��������"),
            new("is_also_known_as_dread_pirate_roberts", "����� �������� ��� ������� ����� �������"),
            new("says_as_you_wish", "������� \"��� ���������\""),
            new("is_skilled_swordsman", "������� ������"),
            new("wears_a_black_mask", "����� ������ �����"),
            new("rescues_a_princess_named_buttercup", "������� ��������� �� ����� �����"),
            new("seeks_revenge", "���� �����"),
            new("says_hello_my_name_is_inigo_montoya", "������� \"������, ���� ����� ����� �������\""),
            new("has_a_scar_on_his_face", "����� ���� �� ����"),
            new("seeks_a_six_fingered_man", "���� ����������� ��������"),
            new("is_from_kansas", "�� �������"),
            new("travels_to_a_magical_land_oz", "������������ � ��������� ������ ��"),
            new("has_a_dog_pet_named_toto", "����� ������-������� �� ����� �������"),
            new("wears_ruby_slippers", "����� ��������� ��������"),
            new("follows_a_yellow_brick_road", "���� �� ������ �� ������� �������"),
            new("from_the_wizard_of_oz", "�� \"���������� ������ ��\""),
            new("is_made_of_straw", "������ �� ������"),
            new("wants_a_brain", "����� �����"),
            new("travels_with_dorothy", "������������ � ������"),
            new("is_flexible", "������"),
            new("is_made_of_tin", "������ �� �����"),
            new("wants_a_heart", "����� ������"),
            new("rusts_easily", "����� �������"),
            new("is_a_lion", "�������� �����"),
            new("wants_courage", "����� ���������"),
            new("is_king_of_the_forest_but_afraid", "������ ����, �� ������"),
            new("is_a_chemistry_teacher_at_first", "������� ������� �����"),
            new("becomes_a_drug_dealer", "���������� ��������������"),
            new("is_diagnosed_with_cancer", "��� ��������������� ���"),
            new("cooks_meth", "����� ���"),
            new("is_known_as_heisenberg", "�������� ��� ����������"),
            new("from_breaking_bad", "�� \"�� ��� ������\""),
            new("shaves_his_head", "����� ������"),
            new("is_partner_of_walter_white", "�������� ��������� ������� �����"),
            new("says_bitch_a_lot", "����� ������� \"bitch\""),
            new("uses_slang", "���������� �����"),
            new("is_younger_than_his_partner", "������ ������ ��������"),
            new("works_in_advertising", "�������� � �������"),
            new("has_a_secret_past", "����� ��������� �������"),
            new("is_good_at_creating_slogans", "������ ����������� �������"),
            new("smokes_and_drinks_a_lot", "����� ����� � ����"),
            new("from_mad_men", "�� \"��������\""),
            new("has_multiple_affairs", "����� ��������� ������� �� �������"),
            new("is_a_mafia_boss", "�������� ������ �����"),
            new("has_panic_attacks", "�������� ����������� �������"),
            new("sees_a_therapist_dr_melfi", "�������� ��������� ������� �����"),
            new("lives_in_new_jersey", "����� � ���-������"),
            new("from_the_sopranos", "�� \"���� �������\""),
            new("has_problems_balancing_family_and_crime", "����� �������� � ��������������� ����� � ���������"),
            new("is_a_doctor", "�������� ��������"),
            new("solves_medical_mysteries", "����������� ����������� �������"),
            new("is_cynical_or_misanthropic", "�������� ��� ��������������"),
            new("is_addicted_to_painkillers_vicodin", "������� �� �������������� (�������)"),
            new("works_at_princeton_plainsboro_teaching_hospital", "�������� � ������� �������� ��������-����������"),
            new("uses_deduction", "���������� ��������"),
            new("lives_at_221b_baker_street", "����� �� ������-����� 221�"),
            new("has_a_doctor_as_a_companion_named_watson", "����� �������-���������� �� ����� ������"),
            new("is_very_intelligent", "����� �����"),
            new("plays_the_violin", "������ �� �������"),
            new("is_a_companion_to_sherlock_holmes", "�������� ����������� ������� ������"),
            new("writes_about_adventures", "����� � ������������"),
            new("from_sherlock_holmes_stories", "�� ��������� � ������� ������"),
            new("was_injured_in_afghanistan", "��� ����� � �����������"),
            new("deyen_ris_targarien", "��������� ���������"), // �������� � �����
            new("has_dragons", "����� ��������"),
            new("has_silver_hair", "����� ���������� ������"),
            new("seeks_the_iron_throne", "���������� ��������� �����"),
            new("is_called_mother_of_dragons", "�� �������� ������� ��������"),
            new("from_game_of_thrones", "�� \"���� ���������\""),
            new("walks_into_fire", "�������� ������ �����"),
            new("dzhon_snou", "���� ����"), // �������� � �����
            new("serves_on_the_night_watch", "������ � ������ ������"),
            new("is_a_bastard_son", "�������� ������������������ �����"),
            new("fights_against_the_dead", "��������� ������ �������"),
            new("has_a_direwolf_pet_named_ghost", "����� ���������-������� �� ����� �������"),
            new("is_from_the_north", "� ������"),
            new("returns_from_death", "������������ �� �������"),
            new("tirion_lannister", "������ ���������"), // �������� � �����
            new("is_a_dwarf_in_size", "������� ����� (������)"),
            new("drinks_a_lot", "����� ����"),
            new("is_from_a_wealthy_and_powerful_family_lannister", "�� ������� � ����������� ����� �����������"),
            new("baffi_sammers", "����� �������"), // �������� � �����
            new("fights_vampires", "��������� � ���������"),
            new("attends_high_school", "����� � ������� �����"),
            new("is_called_the_slayer", "�� �������� ����������������"),
            new("from_buffy_the_vampire_slayer", "�� \"����� - ��������������� ��������\""),
            new("lives_in_sunnydale_california", "����� � ����������, ����������"),
            new("angel_buffy", "����� (�����)"), // �������� � �����
            new("is_a_vampire", "�������� ��������"),
            new("has_a_soul", "����� ����"),
            new("is_in_love_with_buffy_summers", "������� � ����� �������"),
            new("lives_in_los_angeles", "����� � ���-���������"),
            new("from_buffyverse", "�� ��������� \"�����\""),
            new("runs_a_detective_agency", "��������� ����������� ����������"),
            new("maykl_skott", "����� �����"), // �������� � �����
            new("is_a_manager_of_a_paper_company", "�������� ���������� �������� ��������"),
            new("is_socially_awkward", "��������� ��������"),
            new("tries_to_be_funny", "�������� ������"),
            new("from_the_office_us", "�� ������� \"����\" (���)"),
            new("says_thats_what_she_said", "������� \"��� ��, ��� ��� �������\""),
            new("duayt_shrutt", "����� ����"), // �������� � �����
            new("works_at_a_paper_company", "�������� � �������� ��������"),
            new("is_a_salesman", "�������� ���������"),
            new("is_a_beet_farmer", "������, ������������ ������"),
            new("aspires_to_be_manager", "��������� ����� ����������"),
            new("is_assistant_to_the_regional_manager", "�������� ������������� ���������"),
            new("grut", "����"),
            new("male", "�������� ����"),
            new("non_human", "�� �������"),
            new("is_a_tree_like_creature", "������������� ��������"),
            new("can_only_say_i_am_groot", "����� ������� ������ \"� ���� ����\""),
            new("is_friend_of_rocket", "�������� ������ ������"),
            new("is_part_of_guardians_of_the_galaxy", "�������� ������ ������� ���������"),
            new("can_regenerate", "����� ��������������"),
            new("from_marvel", "�� Marvel"),
            new("is_very_strong", "����� �������"),
            new("raketa_yenot", "������ (����)"),
            new("is_a_raccoon", "�������� ������"),
            new("is_genetically_engineered", "����������� �������������"),
            new("is_a_skilled_marksman", "�������� ������ ��������"),
            new("is_friend_of_groot", "�������� ������ �����"),
            new("is_sarcastic", "������������"),
            new("is_a_master_of_explosives", "�������� �������� ����������"),
            new("lyutik_princess_bride", "����� (��������� ������)"),
            new("female", "�������� ����"),
            new("adult", "��������"),
            new("human", "�������"),
            new("is_a_princess", "�������� ����������"),
            new("is_in_love_with_a_farm_boy_named_westley", "�������� � ����������� ����� �� ����� ������"),
            new("is_captured_by_villains", "��������� ��������"),
            new("from_the_princess_bride", "�� \"���������-�������\""),
            new("is_beautiful", "��������"),
            new("uestli_princess_bride", "������ (�������� ����� �������)"),
            new("is_a_farm_boy_at_first", "������� ���������� ������"),
            new("is_also_known_as_dread_pirate_roberts", "����� �������� ��� ������� ����� �������"),
            new("says_as_you_wish", "������� \"��� ���������\""),
            new("is_skilled_swordsman", "������� ������"),
            new("wears_a_black_mask", "����� ������ �����"),
            new("rescues_a_princess_named_buttercup", "������� ��������� �� ����� �����"),
            new("inigo_montoyya", "����� �������"),
            new("is_a_swordsman", "�������� ��������"),
            new("seeks_revenge", "���� �����"),
            new("says_hello_my_name_is_inigo_montoya", "������� \"������, ���� ����� ����� �������\""),
            new("has_a_scar_on_his_face", "����� ���� �� ����"),
            new("seeks_a_six_fingered_man", "���� ����������� ��������"),
            new("doroti_geyl", "������ ����"),
            new("child", "�������"),
            new("is_from_kansas", "�� �������"),
            new("travels_to_a_magical_land_oz", "������������ � ��������� ������ ��"),
            new("has_a_dog_pet_named_toto", "����� ������-������� �� ����� �������"),
            new("wears_ruby_slippers", "����� ��������� ��������"),
            new("follows_a_yellow_brick_road", "���� �� ������ �� ������� �������"),
            new("from_the_wizard_of_oz", "�� \"���������� ������ ��\""),
            new("strashila_oz", "�������� (��������� ������ ��)"),
            new("is_made_of_straw", "������ �� ������"),
            new("wants_a_brain", "����� �����"),
            new("travels_with_dorothy", "������������ � ������"),
            new("is_flexible", "������"),
            new("zheleznyi_drovosek_oz", "�������� �������� (��������� ������ ��)"),
            new("is_made_of_tin", "������ �� �����"),
            new("wants_a_heart", "����� ������"),
            new("rusts_easily", "����� �������"),
            new("truslivyi_lev_oz", "��������� ��� (��������� ������ ��)"),
            new("is_a_lion", "�������� �����"),
            new("wants_courage", "����� ���������"),
            new("is_king_of_the_forest_but_afraid", "������ ����, �� ������"),
            new("uolter_uayt", "������ ����"),
            new("is_a_chemistry_teacher_at_first", "������� ������� �����"),
            new("becomes_a_drug_dealer", "���������� ��������������"),
            new("is_diagnosed_with_cancer", "��� ��������������� ���"),
            new("cooks_meth", "����� ���"),
            new("is_known_as_heisenberg", "�������� ��� ����������"),
            new("from_breaking_bad", "�� \"�� ��� ������\""),
            new("shaves_his_head", "����� ������"),
            new("dzhessi_pinkman", "������ �������"),
            new("is_partner_of_walter_white", "�������� ��������� ������� �����"),
            new("says_bitch_a_lot", "����� ������� \"bitch\""),
            new("uses_slang", "���������� �����"),
            new("is_younger_than_his_partner", "������ ������ ��������"),
            new("don_dreyper", "��� �������"),
            new("works_in_advertising", "�������� � �������"),
            new("has_a_secret_past", "����� ��������� �������"),
            new("is_good_at_creating_slogans", "������ ����������� �������"),
            new("smokes_and_drinks_a_lot", "����� ����� � ����"),
            new("from_mad_men", "�� \"��������\""),
            new("has_multiple_affairs", "����� ��������� ������� �� �������"),
            new("toni_soprano", "���� �������"),
            new("is_a_mafia_boss", "�������� ������ �����"),
            new("has_panic_attacks", "�������� ����������� �������"),
            new("sees_a_therapist_dr_melfi", "�������� ��������� ������� �����"),
            new("lives_in_new_jersey", "����� � ���-������"),
            new("from_the_sopranos", "�� \"���� �������\""),
            new("has_problems_balancing_family_and_crime", "����� �������� � ��������������� ����� � ���������"),
            new("doktor_gregori_haus", "������ ������� ����"),
            new("is_a_doctor", "�������� ��������"),
            new("solves_medical_mysteries", "����������� ����������� �������"),
            new("is_cynical_or_misanthropic", "�������� ��� ��������������"),
            new("is_addicted_to_painkillers_vicodin", "������� �� �������������� (�������)"),
            new("works_at_princeton_plainsboro_teaching_hospital", "�������� � ������� �������� ��������-����������"),
            new("sherlok_holms", "������ �����"),
            new("is_a_detective", "�������� ����������"),
            new("uses_deduction", "���������� ��������"),
            new("lives_at_221b_baker_street", "����� �� ������-����� 221�"),
            new("has_a_doctor_as_a_companion_named_watson", "����� �������-���������� �� ����� ������"),
            new("is_very_intelligent", "����� �����"),
            new("plays_the_violin", "������ �� �������"),
            new("doktor_dzhon_vatson", "������ ���� ������"),
            new("is_a_companion_to_sherlock_holmes", "�������� ����������� ������� ������"),
            new("writes_about_adventures", "����� � ������������"),
            new("from_sherlock_holmes_stories", "�� ��������� � ������� ������"),
            new("was_injured_in_afghanistan", "��� ����� � �����������"),
            new("deyen_ris_targarien", "��������� ���������"),
            new("has_dragons", "����� ��������"),
            new("has_silver_hair", "����� ���������� ������"),
            new("seeks_the_iron_throne", "���������� ��������� �����"),
            new("is_called_mother_of_dragons", "�� �������� ������� ��������"),
            new("from_game_of_thrones", "�� \"���� ���������\""),
            new("walks_into_fire", "�������� ������ �����"),
            new("dzhon_snou", "���� ����"),
            new("serves_on_the_night_watch", "������ � ������ ������"),
            new("is_a_bastard_son", "�������� ������������������ �����"),
            new("fights_against_the_dead", "��������� ������ �������"),
            new("has_a_direwolf_pet_named_ghost", "����� ���������-������� �� ����� �������"),
            new("is_from_the_north", "� ������"),
            new("returns_from_death", "������������ �� �������"),
            new("tirion_lannister", "������ ���������"),
            new("is_a_dwarf_in_size", "������� ����� (������)"),
            new("drinks_a_lot", "����� ����"),
            new("is_from_a_wealthy_and_powerful_family_lannister", "�� ������� � ����������� ����� �����������"),
            new("baffi_sammers", "����� �������"),
            new("fights_vampires", "��������� � ���������"),
            new("has_super_strength", "�������� ����������"),
            new("attends_high_school", "����� � ������� �����"),
            new("is_called_the_slayer", "�� �������� ����������������"),
            new("from_buffy_the_vampire_slayer", "�� \"����� - ��������������� ��������\""),
            new("lives_in_sunnydale_california", "����� � ����������, ����������"),
            new("angel_buffy", "����� (�����)"),
            new("is_a_vampire", "�������� ��������"),
            new("has_a_soul", "����� ����"),
            new("is_in_love_with_buffy_summers", "������� � ����� �������"),
            new("lives_in_los_angeles", "����� � ���-���������"),
            new("from_buffyverse", "�� ��������� \"�����\""),
            new("runs_a_detective_agency", "��������� ����������� ����������"),
            new("maykl_skott", "����� �����"),
            new("is_a_manager_of_a_paper_company", "�������� ���������� �������� ��������"),
            new("is_socially_awkward", "��������� ��������"),
            new("tries_to_be_funny", "�������� ������"),
            new("from_the_office_us", "�� ������� \"����\" (���)"),
            new("says_thats_what_she_said", "������� \"��� ��, ��� ��� �������\""),
            new("duayt_shrutt", "����� ����"),
            new("works_at_a_paper_company", "�������� � �������� ��������"),
            new("is_a_salesman", "�������� ���������"),
            new("is_a_beet_farmer", "������, ������������ ������"),
            new("aspires_to_be_manager", "��������� ����� ����������"),
            new("is_assistant_to_the_regional_manager", "�������� ������������� ���������"),
            new("grut", "����"),
            new("is_a_tree_like_creature", "������������� ��������"),
            new("can_only_say_i_am_groot", "����� ������� ������ \"� ���� ����\""),
            new("is_friend_of_rocket", "�������� ������ ������"),
            new("is_part_of_guardians_of_the_galaxy", "�������� ������ ������� ���������"),
            new("can_regenerate", "����� ��������������"),
            new("is_very_strong", "����� �������"),
            new("raketa_yenot", "������ (����)"),
            new("is_a_raccoon", "�������� ������"),
            new("is_genetically_engineered", "����������� �������������"),
            new("is_a_skilled_marksman", "�������� ������ ��������"),
            new("is_friend_of_groot", "�������� ������ �����"),
            new("is_sarcastic", "������������"),
            new("is_a_master_of_explosives", "�������� �������� ����������"),
            new("lyutik_princess_bride", "����� (��������� ������)"),
            new("is_in_love_with_a_farm_boy_named_westley", "�������� � ����������� ����� �� ����� ������"),
            new("is_captured_by_villains", "��������� ��������"),
            new("from_the_princess_bride", "�� \"���������-�������\""),
            new("is_beautiful", "��������"),
            new("uestli_princess_bride", "������ (�������� ����� �������)"),
            new("is_also_known_as_dread_pirate_roberts", "����� �������� ��� ������� ����� �������"),
            new("says_as_you_wish", "������� \"��� ���������\""),
            new("is_skilled_swordsman", "������� ������"),
            new("wears_a_black_mask", "����� ������ �����"),
            new("rescues_a_princess_named_buttercup", "������� ��������� �� ����� �����"),
            new("inigo_montoyya", "����� �������"),
            new("is_a_swordsman", "�������� ��������"),
            new("seeks_revenge", "���� �����"),
            new("says_hello_my_name_is_inigo_montoya", "������� \"������, ���� ����� ����� �������\""),
            new("has_a_scar_on_his_face", "����� ���� �� ����"),
            new("seeks_a_six_fingered_man", "���� ����������� ��������"),
            new("doroti_geyl", "������ ����"),
            new("is_from_kansas", "�� �������"),
            new("travels_to_a_magical_land_oz", "������������ � ��������� ������ ��"),
            new("has_a_dog_pet_named_toto", "����� ������-������� �� ����� �������"),
            new("wears_ruby_slippers", "����� ��������� ��������"),
            new("follows_a_yellow_brick_road", "���� �� ������ �� ������� �������"),
            new("from_the_wizard_of_oz", "�� \"���������� ������ ��\""),
            new("strashila_oz", "�������� (��������� ������ ��)"),
            new("is_made_of_straw", "������ �� ������"),
            new("wants_a_brain", "����� �����"),
            new("travels_with_dorothy", "������������ � ������"),
            new("is_flexible", "������"),
            new("zheleznyi_drovosek_oz", "�������� �������� (��������� ������ ��)"),
            new("is_made_of_tin", "������ �� �����"),
            new("wants_a_heart", "����� ������"),
            new("rusts_easily", "����� �������"),
            new("truslivyi_lev_oz", "��������� ��� (��������� ������ ��)"),
            new("is_a_lion", "�������� �����"),
            new("wants_courage", "����� ���������"),
            new("is_king_of_the_forest_but_afraid", "������ ����, �� ������"),
            new("uolter_uayt", "������ ����"),
            new("is_a_chemistry_teacher_at_first", "������� ������� �����"),
            new("becomes_a_drug_dealer", "���������� ��������������"),
            new("is_diagnosed_with_cancer", "��� ��������������� ���"),
            new("cooks_meth", "����� ���"),
            new("is_known_as_heisenberg", "�������� ��� ����������"),
            new("from_breaking_bad", "�� \"�� ��� ������\""),
            new("shaves_his_head", "����� ������"),
            new("dzhessi_pinkman", "������ �������"),
            new("is_partner_of_walter_white", "�������� ��������� ������� �����"),
            new("says_bitch_a_lot", "����� ������� \"bitch\""),
            new("uses_slang", "���������� �����"),
            new("is_younger_than_his_partner", "������ ������ ��������"),
            new("don_dreyper", "��� �������"),
            new("works_in_advertising", "�������� � �������"),
            new("has_a_secret_past", "����� ��������� �������"),
            new("is_good_at_creating_slogans", "������ ����������� �������"),
            new("smokes_and_drinks_a_lot", "����� ����� � ����"),
            new("from_mad_men", "�� \"��������\""),
            new("has_multiple_affairs", "����� ��������� ������� �� �������"),
            new("toni_soprano", "���� �������"),
            new("is_a_mafia_boss", "�������� ������ �����"),
            new("has_panic_attacks", "�������� ����������� �������"),
            new("sees_a_therapist_dr_melfi", "�������� ��������� ������� �����"),
            new("lives_in_new_jersey", "����� � ���-������"),
            new("from_the_sopranos", "�� \"���� �������\""),
            new("has_problems_balancing_family_and_crime", "����� �������� � ��������������� ����� � ���������"),
            new("doktor_gregori_haus", "������ ������� ����"),
            new("is_a_doctor", "�������� ��������"),
            new("solves_medical_mysteries", "����������� ����������� �������"),
            new("is_cynical_or_misanthropic", "�������� ��� ��������������"),
            new("is_addicted_to_painkillers_vicodin", "������� �� �������������� (�������)"),
            new("works_at_princeton_plainsboro_teaching_hospital", "�������� � ������� �������� ��������-����������"),
            new("sherlok_holms", "������ �����"),
            new("is_a_detective", "�������� ����������"),
            new("uses_deduction", "���������� ��������"),
            new("lives_at_221b_baker_street", "����� �� ������-����� 221�"),
            new("has_a_doctor_as_a_companion_named_watson", "����� �������-���������� �� ����� ������"),
            new("is_very_intelligent", "����� �����"),
            new("plays_the_violin", "������ �� �������"),
            new("doktor_dzhon_vatson", "������ ���� ������"),
            new("is_a_companion_to_sherlock_holmes", "�������� ����������� ������� ������"),
            new("writes_about_adventures", "����� � ������������"),
            new("from_sherlock_holmes_stories", "�� ��������� � ������� ������"),
            new("was_injured_in_afghanistan", "��� ����� � �����������"),
            new("deyen_ris_targarien", "��������� ���������"),
            new("has_dragons", "����� ��������"),
            new("has_silver_hair", "����� ���������� ������"),
            new("seeks_the_iron_throne", "���������� ��������� �����"),
            new("is_called_mother_of_dragons", "�� �������� ������� ��������"),
            new("from_game_of_thrones", "�� \"���� ���������\""),
            new("walks_into_fire", "�������� ������ �����"),
            new("dzhon_snou", "���� ����"),
            new("serves_on_the_night_watch", "������ � ������ ������"),
            new("is_a_bastard_son", "�������� ������������������ �����"),
            new("fights_against_the_dead", "��������� ������ �������"),
            new("has_a_direwolf_pet_named_ghost", "����� ���������-������� �� ����� �������"),
            new("is_from_the_north", "� ������"),
            new("returns_from_death", "������������ �� �������"),
            new("tirion_lannister", "������ ���������"),
            new("is_a_dwarf_in_size", "������� ����� (������)"),
            new("drinks_a_lot", "����� ����"),
            new("is_from_a_wealthy_and_powerful_family_lannister", "�� ������� � ����������� ����� �����������"),
            new("baffi_sammers", "����� �������"),
            new("fights_vampires", "��������� � ���������"),
            new("has_super_strength", "�������� ����������"),
            new("attends_high_school", "����� � ������� �����"),
            new("is_called_the_slayer", "�� �������� ����������������"),
            new("from_buffy_the_vampire_slayer", "�� \"����� - ��������������� ��������\""),
            new("lives_in_sunnydale_california", "����� � ����������, ����������"),
            new("angel_buffy", "����� (�����)"),
            new("is_a_vampire", "�������� ��������"),
            new("has_a_soul", "����� ����"),
            new("is_in_love_with_buffy_summers", "������� � ����� �������"),
            new("lives_in_los_angeles", "����� � ���-���������"),
            new("from_buffyverse", "�� ��������� \"�����\""),
            new("runs_a_detective_agency", "��������� ����������� ����������"),
            new("maykl_skott", "����� �����"),
            new("is_a_manager_of_a_paper_company", "�������� ���������� �������� ��������"),
            new("is_socially_awkward", "��������� ��������"),
            new("tries_to_be_funny", "�������� ������"),
            new("from_the_office_us", "�� ������� \"����\" (���)"),
            new("says_thats_what_she_said", "������� \"��� ��, ��� ��� �������\""),
            new("duayt_shrutt", "����� ����"),
            new("works_at_a_paper_company", "�������� � �������� ��������"),
            new("is_a_salesman", "�������� ���������"),
            new("is_a_beet_farmer", "������, ������������ ������"),
            new("aspires_to_be_manager", "��������� ����� ����������"),
            new("is_assistant_to_the_regional_manager", "�������� ������������� ���������")
        };


        public GameModel(IHttpClientFactory clientFactory)
        {
            _clientFactory = clientFactory;
        }

        [BindProperty]
        public required string Answer { get; set; }

        [BindProperty]
        public required string CurrentQuestionText { get; set; }

        public bool Finished { get; set; } = false;

        [BindProperty]
        public required string FinalResult { get; set; }

        public async Task<IActionResult> OnGetAsync()
        {
            //  
            HttpContext.Session.SetInt32("CurrentIndex", 0);
            HttpContext.Session.SetString("YesAnswers", JsonSerializer.Serialize(new List<string>()));

            CurrentQuestionText = $"��� �������� {OrderedAttributes[0].Text}?";
            return Page();
        }

        private void SaveSession(string username, string characterName)
        {
            if (string.IsNullOrEmpty(username) || string.IsNullOrEmpty(characterName))
                return;

            using var conn = new SqliteConnection("Data Source=akinator.db");
            conn.Open();

            using var cmd = conn.CreateCommand();
            cmd.CommandText = @"
                INSERT INTO Sessions (UserId, CharacterName, StartedAt)
                SELECT Id, @CharacterName, @StartedAt
                FROM Users
                WHERE Username = @Username";

            cmd.Parameters.AddWithValue("@Username", username);
            cmd.Parameters.AddWithValue("@CharacterName", characterName);
            cmd.Parameters.AddWithValue("@StartedAt", DateTime.UtcNow);

            cmd.ExecuteNonQuery();
        }



        public async Task<IActionResult> OnPostAsync()
        {
            var username = HttpContext.Session.GetString("Username");
            if (string.IsNullOrEmpty(username))
                return RedirectToPage("/Login");

            var currentIndex = HttpContext.Session.GetInt32("CurrentIndex") ?? 0;
            var yesAnswers = JsonSerializer.Deserialize<List<string>>(
                HttpContext.Session.GetString("YesAnswers") ?? "[]"
            ) ?? new List<string>();

            if (Answer == "yes")
            {
                yesAnswers.Add(OrderedAttributes[currentIndex].Code);
            }

            currentIndex++;

            if (currentIndex >= OrderedAttributes.Count)
            {
                Finished = true;
                FinalResult = "Игра окончена!";
                return Page();
            }

            HttpContext.Session.SetInt32("CurrentIndex", currentIndex);
            HttpContext.Session.SetString("YesAnswers", JsonSerializer.Serialize(yesAnswers));

            CurrentQuestionText = OrderedAttributes[currentIndex].Text;
            return Page();
        }

        public class AttributeItem
        {
            public string Code { get; set; }
            public string Text { get; set; }

            public AttributeItem(string code, string text)
            {
                Code = code;
                Text = text;
            }
        }
    }
}
